### ISSUE TITLE
Docker run with aerospike user and password

### ISSUE THREAD

**Issue by rerime** [aerospike/aerospike-prometheus-exporter#25]
Hi!
How to run docker with user and password in aerospike DB?
Can't find in https://github.com/aerospike/aerospike-prometheus-exporter/blob/master/docker-entrypoint.sh

Also I found in a template
https://github.com/aerospike/aerospike-prometheus-exporter/blob/master/ape.toml.template
```
# database user
user="${AS_AUTH_USER}"

# database password
password="$AS_AUTH_USER"
```
Thx!

**Comment by Xaelias** [comment]
I'm not sure I understand the question.
Are you asking how to run aerospike itself with a user/password? If so that's really not the best place to ask :-)
1/ It's an aerospike EE feature
2/ You need to enable security in the config of AS* https://www.aerospike.com/docs/reference/configuration/#enable-security
3/ You need to create accounts https://www.aerospike.com/docs/operations/configure/security/access-control

If you're talking about the exporter. Well you found it. Just put the username/password for your stats read only account in there and you should be good.

**Comment by spkesan** [comment]
@rerime Thanks for reporting this. 

In `ape.toml.template` it should be 
```
# database password
password="$AS_AUTH_PASSWORD"
```
And the entrypoint script should also be updated. We will fix it.

**Comment by spkesan** [comment]
@rerime 
Fixed on `master`.
The next docker image release will have these changes.
https://hub.docker.com/r/aerospike/aerospike-prometheus-exporter

Thanks again for reporting this. Close this issue...
