### ISSUE TITLE
Latencies metrics not available

### ISSUE THREAD

**Issue by gunjansharma** [aerospike/aerospike-prometheus-exporter#32]
I am using CE 5.1.0.4 vs of aerospike and 1.1.1 APE. But I am getting latency histograms in the metrics.
Albot on the Aerospike confirmed it is a bug.

More details here: https://discuss.aerospike.com/t/not-able-to-get-udf-latency-metrics-with-ce-5-1-0-4-with-prometheus-exporter/7763

**Comment by gunjansharma** [comment]
Here is the bug https://github.com/aerospike/aerospike-prometheus-exporter/blob/5487eac2c2c1beade9847e1440dda28bf3ab6c83/latency_parser.go#L20
There is no semi-colon with new version.
Here is the output of 
asadm -e 'asinfo -v "latency:" -l'
```
{ns1}-read:
{ns1}-write:
{ns1}-udf:
{ns1}-query:
{ns2}-read:msec,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
{ns2}-write:
{ns2}-udf:msec,2103.1,2.42,0.68,0.28,0.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
{ns2}-query:
```

**Comment by khaf** [comment]
`asinfo -v "latency:"` returns the original string, and it has the semi-colon.

**Comment by gunjansharma** [comment]
@khaf I have updated the bug. Please check again. 
I added
```
if err := ip.Expect(";"); err == nil {
  continue
}
```
in latency_parser to fix this temporarily

**Comment by khaf** [comment]
@gunjansharma would it work if you changed this `break`:
https://github.com/aerospike/aerospike-prometheus-exporter/blob/5487eac2c2c1beade9847e1440dda28bf3ab6c83/latency_parser.go#L45

to `continue`?

**Comment by gunjansharma** [comment]
@khaf No, because there is "comma" later in the string for a different namespace and different operation.

**Comment by spkesan** [comment]
Hi @gunjansharma 

Thanks for reporting this. I did take a look at this issue.
The output of `latency:` info command has changed in 5.1 for when there's no latency data.

When there's no data, instead of `error-no-data-yet-or-back-too-small`, aerospike now returns an empty output like this `batch-index:;{test}-read:;{test}-write:;{test}-udf:;{test}-query:` which is breaking the parser.

I think we will apply the fix what you have done... Let's see.

**Comment by gunjansharma** [comment]
@spkesan While you are doing that might I suggest moving away from latency to latencies. Since latency is going to get deprecated soon?

**Comment by khaf** [comment]
@spkesan I think we should also query for the `latencies:` as well, and fall back to `latency:` if it was empty.

**Comment by spkesan** [comment]
Hi @gunjansharma 
This issue has been fixed in the latest release and also the exporter will now use `latencies:` info command against Aerospike versions 5.1 and above.
https://www.aerospike.com/download/monitoring/aerospike-prometheus-exporter/notes.html#1.1.2

Thanks again for reporting. I'll go ahead and close this issue.
